// autogenerated: do not edit!
// generated from weebgen js.min.js

// +build !js

package main

import "github.com/platinasystems/weeb"

func init() {
	c := &weeb.Content{
		URLPath:              "/js/js.min.js",
		UnixTimeLastModified: 1447457446, // 2015-11-13 23:30:46.63846586 +0000 UTC
		ContentType:          "text/javascript",
		ContentEncoding:      "gzip",
		FilePath:             "./js_min_js.gz",
	}
	c.Register()
}
