// autogenerated: do not edit!
// generated from weebgen js.min.js

// +build !js

package main

import "weeb"

func init() {
	c := &weeb.Content{
		URLPath:              "/js/js.min.js",
		UnixTimeLastModified: 1447455002, // 2015-11-13 22:50:02.312331191 +0000 UTC
		ContentType:          "text/javascript",
		ContentEncoding:      "gzip",
		FilePath:             "./js_min_js.gz",
	}
	c.Register()
}
