// autogenerated: do not edit!
// generated from weebgen internal/js/foundation/foundation.min.js

// +build !js

package foundation_min_js

import "github.com/platinasystems/weeb"

func init() {
	c := &weeb.Content{
		URLPath:              "/js/foundation.min.js",
		UnixTimeLastModified: 1447457446, // 2015-11-13 23:30:46.199665884 +0000 UTC
		ContentType:          "text/javascript",
		ContentEncoding:      "gzip",
		FilePath:             "internal/js/foundation/foundation_min_js.gz",
	}
	c.Register()
}
