// autogenerated: do not edit!
// generated from weebgen internal/js/foundation/foundation.min.js

// +build !js

package foundation_min_js

import "github.com/platinasystems/weeb"

func init() {
	c := &weeb.Content{
		URLPath:              "/js/foundation.min.js",
		UnixTimeLastModified: 1447625089, // 2015-11-15 22:04:49.934221149 +0000 UTC
		ContentType:          "text/javascript",
		ContentEncoding:      "gzip",
		FilePath:             "internal/js/foundation/foundation_min_js.gz",
	}
	c.Register()
}
