// autogenerated: do not edit!
// generated from weebgen internal/css/eg/eg.min.css

// +build !js

package eg_min_css

import "weeb"

func init() {
	c := &weeb.Content{
		URLPath:              "/css/eg.min.css",
		UnixTimeLastModified: 1447455001, // 2015-11-13 22:50:01.80268589 +0000 UTC
		ContentType:          "text/css",
		ContentEncoding:      "gzip",
		FilePath:             "internal/css/eg/eg_min_css.gz",
	}
	c.Register()
}
