// autogenerated: do not edit!
// generated from weebgen internal/css/eg/eg.min.css

// +build !js

package eg_min_css

import "github.com/platinasystems/weeb"

func init() {
	c := &weeb.Content{
		URLPath:              "/css/eg.min.css",
		UnixTimeLastModified: 1447625089, // 2015-11-15 22:04:49.948173836 +0000 UTC
		ContentType:          "text/css",
		ContentEncoding:      "gzip",
		FilePath:             "internal/css/eg/eg_min_css.gz",
	}
	c.Register()
}
