// autogenerated: do not edit!
// generated from weebgen internal/js/foundation_deps/foundation_deps.min.js

// +build !js

package foundation_deps_min_js

import "weeb"

func init() {
	c := &weeb.Content{
		URLPath:              "/js/foundation_deps.min.js",
		UnixTimeLastModified: 1447455001, // 2015-11-13 22:50:01.768365336 +0000 UTC
		ContentType:          "text/javascript",
		ContentEncoding:      "gzip",
		FilePath:             "internal/js/foundation_deps/foundation_deps_min_js.gz",
	}
	c.Register()
}
